# Generated by Django 3.1.6 on 2021-07-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=150)),
                ('birthday', models.DateField()),
                ('city', models.CharField(blank=True, max_length=50)),
                ('AdrLive', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateVisit', models.DateField(blank=True, null=True, verbose_name='День записи')),
                ('TimeVisit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время записи')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatDiary.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Дата записи',
                'verbose_name_plural': 'Даты записи',
                'ordering': ['DateVisit', 'TimeVisit'],
            },
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лечения')),
                ('treatment', models.TextField(blank=True, max_length=400)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatDiary.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Лечение',
                'verbose_name_plural': 'Лечения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PatDiary.patient')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth18', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='18')),
                ('tooth17', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='17')),
                ('tooth16', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='16')),
                ('tooth15', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='15')),
                ('tooth14', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='14')),
                ('tooth13', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='13')),
                ('tooth12', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='12')),
                ('tooth11', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='11')),
                ('tooth21', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='21')),
                ('tooth22', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='22')),
                ('tooth23', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='23')),
                ('tooth24', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='24')),
                ('tooth25', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='25')),
                ('tooth26', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='26')),
                ('tooth27', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='27')),
                ('tooth28', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='28')),
                ('tooth38', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='38')),
                ('tooth37', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='37')),
                ('tooth36', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='36')),
                ('tooth35', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='35')),
                ('tooth34', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='34')),
                ('tooth33', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='33')),
                ('tooth32', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='32')),
                ('tooth31', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='31')),
                ('tooth41', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='41')),
                ('tooth42', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='42')),
                ('tooth43', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='43')),
                ('tooth44', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='44')),
                ('tooth45', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='45')),
                ('tooth46', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='46')),
                ('tooth47', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='47')),
                ('tooth48', models.CharField(blank=True, choices=[('', ''), ('Ca', 'C'), ('P', 'P'), ('Pt', 'Pt'), ('EX', 'A'), ('Cd', 'Cd'), ('Ar', 'Ar')], max_length=20, verbose_name='48')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PatDiary.patient')),
            ],
            options={
                'verbose_name': 'Формула зубов',
                'verbose_name_plural': 'Формулы зубов',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(blank=True, max_length=150, null=True, verbose_name='Жалобы')),
                ('anamnes', models.CharField(blank=True, max_length=150, null=True, verbose_name='Анамнез')),
                ('StLocalis', models.CharField(blank=True, max_length=150, null=True, verbose_name='Общий осмотр')),
                ('PreDiagnose', models.CharField(blank=True, max_length=150, null=True, verbose_name='Предварительный диагноз')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PatDiary.patient')),
            ],
            options={
                'verbose_name': 'Обследование',
                'verbose_name_plural': 'Обследования',
            },
        ),
    ]
